# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Entrepreneur Challenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Entrepreneur Challenge
  
  pod 'Alamofire', '~> 4.4'
  pod 'SwiftyJSON', '~> 3.1'
  pod 'Kingfisher', '~> 3.5'
  pod 'AlamofireImage', '~> 3.2'
  pod 'FloatRatingView', '~> 2.0'
  pod 'PieCharts'

  target 'Entrepreneur ChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Entrepreneur ChallengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
